modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/anviaan/GlowInkPlus/issues"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL="https://api.modrinth.com/updates/glow-ink-plus/forge_updates.json"
displayURL="https://modrinth.com/mod/glow-ink-plus"
logoFile="${mod_id}.png"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
